CPPFLAGS= -std=c++20 -O2 -Wall

runc:
	@ g++ -g $(f).cpp $(CPPFLAGS) -o main
	@ ./main

runci:
	@ g++ -g $(f).cpp $(CPPFLAGS) -o main
	@ ./main < input.txt

runp:
	@ python3 $(f).py

runpt:
	@ python3 $(f).py < input.txt